nohup python train.py --epochs 300 \
                      --batch_size 256 \
                      --lr 0.0002 \
                      --img_size 32 \
                      --channels 3 \
                      --sample_interval 50 \
                      --b1 0.5 \
                      --b2 0.999 \
                      --model Diffusion_Model \
                      --save_model_path /home/wangchai/zhw/Generative-Model/ckpt/Diffusion_Model.pth \
                      --dataset_path /home/wangchai/zhw/Generative-Model/dataset > train_Diffusion_Model.log 2>&1 &